// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTasks(arg1:number):Promise<string>;

export function GetTasks():Promise<string>;

export function NewTask(arg1:string,arg2:number):Promise<string>;

export function SaveTasks():Promise<void>;

export function UpdateTasks(arg1:number,arg2:boolean,arg3:number):Promise<string>;
