// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTasks(arg1) {
  return window['go']['tracker']['Tasks']['DeleteTasks'](arg1);
}

export function GetTasks() {
  return window['go']['tracker']['Tasks']['GetTasks']();
}

export function NewTask(arg1, arg2) {
  return window['go']['tracker']['Tasks']['NewTask'](arg1, arg2);
}

export function SaveTasks() {
  return window['go']['tracker']['Tasks']['SaveTasks']();
}

export function UpdateTasks(arg1, arg2, arg3) {
  return window['go']['tracker']['Tasks']['UpdateTasks'](arg1, arg2, arg3);
}
